# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('adress', models.CharField(max_length=250)),
                ('date', models.DateTimeField(verbose_name='Data do evento')),
            ],
        ),
    ]
