# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='adress',
            new_name='address',
        ),
    ]
