# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170612_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('isFromCEFET', models.BooleanField()),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
