# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170701_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
