# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_spectator_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora do evento'),
        ),
    ]
