# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170705_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='Hora do evento'),
        ),
    ]
