# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170706_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='beginTime',
            field=models.TimeField(default=None, verbose_name='Horário de início do evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=None, verbose_name='Horário de término do evento'),
        ),
    ]
