# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170706_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='beginTime',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Horário de início do evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Horário de término do evento'),
        ),
    ]
