# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_spectator_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Momento da inscrição'),
        ),
    ]
