# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_spectator_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectator',
            name='enrollNumber',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
