# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_spectator_enrollnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectator',
            old_name='enrollNumber',
            new_name='enrollNum',
        ),
    ]
