# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170711_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='spectator',
            name='occupation',
            field=models.CharField(max_length=80),
        ),
    ]
