# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('roman_id', models.CharField(max_length=2)),
            ],
        ),
    ]
