# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cefet', '0002_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'campi'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='roman_id',
            field=models.CharField(editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cefet.Campus'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cefet.Course'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
