# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cefet', '0003_auto_20160921_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='campus',
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cefet.Campus'),
        ),
    ]
