# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cefet', '0004_auto_20160921_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cefet.Campus'),
        ),
    ]
