# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 16:19
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('text_call', models.CharField(max_length=255, verbose_name='Descrição')),
                ('text_content', models.TextField(verbose_name='Conteúdo')),
                ('thumbnail', models.ImageField(upload_to=blog.models.get_image_path, verbose_name='Thumbnail')),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('last_modification', models.DateField(auto_now=True)),
                ('publish_as_team', models.BooleanField(default=False, verbose_name='Postar em nome da equipe')),
                ('member', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Member')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
