# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 11:52
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_image_path, verbose_name='Thumbnail'),
        ),
    ]
