# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('text_call', models.CharField(max_length=255)),
                ('text_content', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('last_modification', models.DateField(auto_now=True)),
            ],
        ),
    ]
