# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:57
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(height_field=100, upload_to=blog.models.get_image_path, width_field=100),
        ),
    ]
