# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:11
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160820_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='thumbnail',
            field=models.ImageField(upload_to=blog.models.get_image_path),
        ),
    ]
