# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160820_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.CharField(default='compet', max_length=255),
            preserve_default=False,
        ),
    ]
