# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='user',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
