# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160821_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='my-publications',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('blog.publication',),
        ),
    ]
