# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_my-publications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my-publications',
        ),
        migrations.CreateModel(
            name='MyPublication',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('blog.publication',),
        ),
    ]
