# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160829_1653'),
        ('blog', '0010_auto_20160821_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
    ]
