# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_publication_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Author'),
        ),
    ]
