# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160829_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='member',
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Author'),
        ),
    ]
