# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload_helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to=utils.upload_helper.get_image_path, verbose_name='Foto')),
                ('facebook_link', models.CharField(blank=True, max_length=255, verbose_name='Link do Facebook')),
                ('lattes_link', models.CharField(blank=True, max_length=255, verbose_name='Link do Lattes')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='E-mail')),
            ],
            options={
                'verbose_name_plural': 'Membros (todos)',
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('name_plural', models.CharField(max_length=255, unique=True, verbose_name='Plural')),
            ],
            options={
                'verbose_name': 'Papel do membro',
                'verbose_name_plural': 'Papéis dos membros',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.MemberRole', verbose_name='Papel'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MyMember',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Membro',
            },
            bases=('members.member',),
        ),
    ]
