# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_link',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='member',
            name='lattes_link',
            field=models.TextField(default='none'),
        ),
    ]
