# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20160827_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMember',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('members.member',),
        ),
    ]
