# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_mymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
