# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20160827_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.CharField(default='user', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
