# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook_link',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='lattes_link',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to=members.models.get_image_path),
        ),
    ]
