# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160829_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('MB', 'Membro'), ('EM', 'Ex-Membro'), ('TT', 'Tutor'), ('VT', 'Voluntário')], default='MB', max_length=2),
        ),
    ]
