# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160829_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='lattes_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
