# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 16:18
from __future__ import unicode_literals

import cefet.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número')),
                ('location', models.CharField(max_length=255, verbose_name='Cidade')),
                ('roman_id', models.CharField(editable=False, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'campi',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cefet.Campus')),
            ],
            options={
                'verbose_name': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=cefet.models.get_image_path, verbose_name='Foto')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Data de criação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cefet.Course', verbose_name='Curso')),
            ],
            options={
                'verbose_name_plural': 'PETs',
            },
        ),
    ]
