# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cefet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
    ]
