# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cefet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to=members.models.get_image_path, verbose_name='Foto')),
                ('facebook_link', models.CharField(blank=True, max_length=255, verbose_name='Link do Facebook')),
                ('lattes_link', models.CharField(blank=True, max_length=255, verbose_name='Link do Lattes')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='cefet.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('verbose_name', models.CharField(max_length=255, blank=True)),
                ('verbose_name_plural', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'verbose_name_plural': 'Funções dos membros',
                'verbose_name': 'Função do membro',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.MemberRole', verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
