# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='verbose_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='verbose_name_plural',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
