# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20170114_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='cefet.Pet'),
        ),
    ]
