# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170114_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'membro'},
        ),
        migrations.AlterModelOptions(
            name='memberrole',
            options={'verbose_name': 'função do membro', 'verbose_name_plural': 'funções dos membros'},
        ),
        migrations.AddField(
            model_name='member',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de saída do PET'),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrada no PET'),
        ),
    ]
